image: docker

stages:
  - build

before_script:
  - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

build-api:
  stage: build
  script:
    - docker build -t jackhaynes/cloud-fib-api ./api
    - docker push jackhaynes/cloud-fib-api

build-worker:
  stage: build
  script:
    - docker build -t jackhaynes/cloud-fib-worker ./worker
    - docker push jackhaynes/cloud-fib-worker
