image: docker:18

stages:
  - build

build-api:
  stage: build
  script:
    - docker build -t jackhaynes/cloud-fib-api:latest ./api

build-worker:
  stage: build
  script:
    - docker build -t jackhaynes/cloud-fib-worker:latest ./worker
