version: '3'

services:
  proxy:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./proxy
    ports:
      - '8080:80'

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /app/venv
      - ./api/:/app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672

  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/venv
      - ./worker/:/app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
