version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    ports:
      - '8080:5000'
    volumes:
      - /app/venv
      - ./api/:/app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672

  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/venv
      - ./worker/:/app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - "5672:5672"
        - "15672:15672"
