version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - '8080:5000'
    volumes:
      - /venv
      - .:/app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - "5672:5672"
        - "15672:15672"