version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - '8080:5000'
    volumes:
      - /venv
      - .:/app


  rabbitmq:
    image: rabbitmq:3.9-alpine
    ports:
      - '8081:5672'