FROM python:3.9-alpine

WORKDIR /app

# Install dependencies.
COPY ./requirements.txt ./requirements.txt
RUN pip install -r requirements.txt

# Copy project files into container.
COPY . .

# Setup Flask environment variables.
ENV FLASK_APP=app.py
ENV FLASK_ENV=development

EXPOSE 5000

# Run Flask development server.
CMD ["python", "-m", "flask", "run", "--host", "0.0.0.0"]